name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      xvfb: # X virtual framebuffer
        image: selenium/standalone-chrome
        options: --shm-size 2g

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      working-directory: ./
      run: |
        npm install
        
    - name: Install spec dependencies
      working-directory: ./spec
      run: |
        npm install

    - name: Run spec
      working-directory: ./spec
      run: npm run test
